### ISSUE TITLE
[Request] Cleanup vehicle and logistics spawner

### ISSUE THREAD

**Issue by gelir95** [Brig13Team/Operation_Kerberos#225]
Logistics spawner (USS Freedom) :

Remove:
- M1232
- M1232(M2)
- M1232(MK19)
- M1237(M2)
- M1237(MK19)

Add:
- spare tracks
- spare wheel

Aircraft Spawner (USS Freedom):

Remove:
- UGV Stomper
- UGV Stomper RCWS
- Praetorian 1C
- MK49 Spartan
- MK21 Centurion
- AR-2 Darter

Vehicle Spawner (Tonos Bay)

Remove:
- M252
- Huron Ammo Container
- Huron Cargo Container
- Huron Fuel Container
- Huron Medical Container
- Huron Repair Container
- XM312
- XM312 (high)
- XM312A
- XM307
- XM307(high)
- XM307A
- MK6 Mortar
- Mini-Spike Launcher (AA)
- Mini-Spike Launcher (AT)
- Remote Designator [NATO]
- M2HB (M3 AA)
- M2HB (M3)
- MK19 (M3)
- M41A4 TOW
- FIM-92F (DMS)
- Spotting Scope
- Vehicle Ammo [Nato]

Maybe remove:
- logistics vehicles

Add:
- UGV Stomper
- UGV Stomper RCWS

**Comment by Dorbedo** [comment]
Carrier-Vehicles:
- [x] add tracks, wheels
- [ ] remove M1232,M1237

Carrier-Air
- [x] remove AA
The other changes won't be done, because the Autonomous vehicles can be Airlifted and 

Landbase:
- [ ] add UGVs
- [ ] remove spotting scope
The logistic Vehicles and statics won't be removed since they can be loaded on vehicles while beeing assambled.
Logistics vehicles should be availlible for transporting things via land without need to be airlifted.
